---
# Example host-specific overrides for a personal Linux VM.

os_linux_machine_profile: vm

bootstrap_git_user_name: "HexSleeves"
bootstrap_git_user_email: "lecoqjacob@gmail.com"
chezmoi_repo: "https://github.com/HexSleeves/dotfiles.git"
