---
- name: Check for Homebrew (Apple Silicon)
  ansible.builtin.stat:
    path: /opt/homebrew/bin/brew
  register: os_macos_brew_opt

- name: Check for Homebrew (Intel)
  ansible.builtin.stat:
    path: /usr/local/bin/brew
  register: os_macos_brew_usr

- name: Install Homebrew
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /opt/homebrew/bin/brew
  when: not os_macos_brew_opt.stat.exists and not os_macos_brew_usr.stat.exists

- name: Add Homebrew to PATH for Apple Silicon
  ansible.builtin.lineinfile:
    path: "{{ ansible_facts['env']['HOME'] }}/.zprofile"
    line: 'eval "$(/opt/homebrew/bin/brew shellenv)"'
    create: true
    mode: "0644"
  when: ansible_facts['machine'] == 'arm64'

- name: Install Homebrew packages
  community.general.homebrew:
    name: "{{ os_macos_homebrew_packages }}"
    state: present

- name: Prompt to install Homebrew casks
  ansible.builtin.pause:
    prompt: "Do you want to install Homebrew casks? (y/N)"
  register: os_macos_cask_prompt

- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ os_macos_homebrew_casks }}"
    state: present
  when: os_macos_cask_prompt.user_input | lower in ['y', 'yes']

- name: Set macOS defaults
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ os_macos_defaults }}"
