---
- name: Check for Homebrew (Apple Silicon)
  ansible.builtin.stat:
    path: /opt/homebrew/bin/brew
  register: brew_opt

- name: Check for Homebrew (Intel)
  ansible.builtin.stat:
    path: /usr/local/bin/brew
  register: brew_usr

- name: Install Homebrew
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /opt/homebrew/bin/brew
  when: not brew_opt.stat.exists and not brew_usr.stat.exists

- name: Add Homebrew to PATH for Apple Silicon
  ansible.builtin.lineinfile:
    path: "{{ ansible_facts['env']['HOME'] }}/.zprofile"
    line: 'eval "$(/opt/homebrew/bin/brew shellenv)"'
    create: true
  when: ansible_facts['machine'] == 'arm64'

- name: Install Homebrew packages
  community.general.homebrew:
    name: "{{ homebrew_packages }}"
    state: present

- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ homebrew_casks }}"
    state: present

- name: Set macOS defaults
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ macos_defaults }}"
