---
# Linux desktop-oriented variables

os_linux_apt_packages:
  - bat
  - fd-find
  - ripgrep
  - fzf
  - jq
  - build-essential
  - git
  - curl
  - wget
  - vim
  - neovim
  - tmux
  - zsh
  - python3
  - python3-pip
  - golang-go
  - htop
  - iotop
  - ncdu
  - tree
  - unzip
  - zip
  - net-tools
  - openssh-server

os_linux_dnf_packages:
  - bat
  - fd-find
  - ripgrep
  - fzf
  - jq
  - "@development-tools"
  - git
  - curl
  - wget
  - vim-enhanced
  - neovim
  - tmux
  - zsh
  - python3
  - python3-pip
  - golang
  - htop
  - iotop
  - ncdu
  - tree
  - unzip
  - zip
  - net-tools
  - openssh-server

# Optional; only installs if snap is present.
os_linux_snap_packages: []
